[32mINFO    [0m pytest_operator.plugin:plugin.py:766 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_smoke:test_smoke.py:65 Deploying bundle
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm data-integrator from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-router-k8s from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-test-app from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm s3-integrator from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm self-signed-certificates from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm sysbench from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm grafana-agent-k8s from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-k8s from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application data-integrator with 1 unit using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-113
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-k8s with 1 unit using $addCharm-11
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-router-k8s-627
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-test-app using $addCharm-14
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/mysql-test-app-74
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application s3-integrator with 1 unit using $addCharm-17
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/s3-integrator-145
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application self-signed-certificates with 1 unit using $addCharm-20
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-266
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application sysbench with 1 unit using $addCharm-23
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/sysbench-171
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application grafana-agent-k8s with 1 unit using $addCharm-3
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-k8s-116
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-k8s with 3 units using $addCharm-6
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-k8s-249
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-data-integrator with 1 unit using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-113
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-12:backend-database
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> mysql-router-k8s:backend-database
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:certificates - $deploy-21:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:certificates - $deploy-21:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:s3-parameters - $deploy-18:s3-credentials
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:s3-parameters <-> s3-integrator:s3-credentials
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-1:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-24:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> sysbench:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:grafana-dashboard - $deploy-4:grafana-dashboards-consumer
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:grafana-dashboard <-> grafana-agent-k8s:grafana-dashboards-consumer
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:metrics-endpoint - $deploy-4:metrics-endpoint
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:metrics-endpoint <-> grafana-agent-k8s:metrics-endpoint
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:logging - $deploy-4:logging-provider
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:logging <-> grafana-agent-k8s:logging-provider
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:database - $deploy-9:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:database <-> mysql-router-data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:grafana-dashboard - $deploy-4:grafana-dashboards-consumer
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:grafana-dashboard <-> grafana-agent-k8s:grafana-dashboards-consumer
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:metrics-endpoint - $deploy-4:metrics-endpoint
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:metrics-endpoint <-> grafana-agent-k8s:metrics-endpoint
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:logging - $deploy-4:logging-provider
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:logging <-> grafana-agent-k8s:logging-provider
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-9
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-12
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-15
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-18
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-1
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-21
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-24
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-4
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-7
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.4    unsupported  01:46:12Z

App                           Version                  Status   Scale  Charm                     Channel      Rev  Address         Exposed  Message
data-integrator                                        blocked      1  data-integrator           latest/edge  113  10.152.183.82   no       Please specify either topic, index, or database name
grafana-agent-k8s             0.40.4                   blocked      1  grafana-agent-k8s         latest/edge  116  10.152.183.227  no       Missing ['grafana-cloud-config']|['grafana-dashboards-provider'] for grafana-dashboards-consumer; ['grafana-cloud-con...
mysql-k8s                                              error        3  mysql-k8s                 8.0/edge     249  10.152.183.60   no       hook failed: "logging-relation-created"
mysql-router-data-integrator                           blocked      1  data-integrator           latest/edge  113  10.152.183.107  no       Please specify either topic, index, or database name
mysql-router-k8s              8.0.41-0ubuntu0.22.04.1  waiting      1  mysql-router-k8s          8.0/edge     627  10.152.183.31   no       installing agent
mysql-test-app                                         unknown      0  mysql-test-app            latest/edge   74  10.152.183.104  no       
s3-integrator                                          blocked      1  s3-integrator             latest/edge  145  10.152.183.137  no       Missing parameters: ['access-key', 'secret-key']
self-signed-certificates                               active       1  self-signed-certificates  latest/edge  266  10.152.183.92   no       
sysbench                                               waiting      1  sysbench                  latest/edge  171  10.152.183.28   no       installing agent

Unit                             Workload  Agent  Address      Ports  Message
data-integrator/0*               blocked   idle   10.1.249.8          Please specify either topic, index, or database name
grafana-agent-k8s/0*             blocked   idle   10.1.249.18         Missing ['grafana-cloud-config']|['grafana-dashboards-provider'] for grafana-dashboards-consumer; ['grafana-cloud-con...
mysql-k8s/0*                     error     idle   10.1.249.19         hook failed: "logging-relation-created"
mysql-k8s/1                      error     idle   10.1.249.21         hook failed: "logging-relation-created"
mysql-k8s/2                      error     idle   10.1.249.20         hook failed: "logging-relation-created"
mysql-router-data-integrator/0*  blocked   idle   10.1.249.13         Please specify either topic, index, or database name
mysql-router-k8s/0*              waiting   idle   10.1.249.9          
s3-integrator/0*                 blocked   idle   10.1.249.10         Missing parameters: ['access-key', 'secret-key']
self-signed-certificates/0*      active    idle   10.1.249.11         
sysbench/0*                      waiting   idle   10.1.249.12         Waiting on data from relation

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-mysql-router-k8s-0: 01:26:50 ERROR unit.mysql-router-k8s/0.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/charm.py", line 448, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 283, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 149, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 118, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 1008, in generate_csr
    _sans.extend([x509.IPAddress(IPv4Address(san)) for san in sans_ip])
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 1008, in <listcomp>
    _sans.extend([x509.IPAddress(IPv4Address(san)) for san in sans_ip])
  File "/usr/lib/python3.10/ipaddress.py", line 1305, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.10/ipaddress.py", line 1192, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'None'
unit-mysql-router-k8s-0: 01:26:50 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:27:38 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:27:38 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:27:39 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:27:39 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:39 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:27:39 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:27:45 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:27:45 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:45 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:27:45 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:27:45 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:27:46 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:27:56 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:27:56 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:57 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:27:57 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:27:57 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:27:57 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:28:18 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:28:19 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:28:20 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:28:20 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:28:20 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:28:20 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:28:58 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:28:59 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:28:59 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:28:59 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:29:01 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:29:01 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:30:16 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:30:16 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:30:17 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:30:17 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:30:23 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:30:23 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:32:45 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:32:46 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:32:48 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:32:48 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:33:06 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:33:06 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:37:47 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:37:47 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:37:47 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:37:47 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:38:07 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:38:07 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:42:48 ERROR unit.mysql-k8s/0.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-2: 01:42:48 ERROR unit.mysql-k8s/2.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-0: 01:42:48 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:42:48 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:43:08 ERROR unit.mysql-k8s/1.juju-log logging:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1101, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 101, in _cos_relation_created
    self.setup()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/log_rotation_setup.py", line 54, in setup
    self.charm._mysql.setup_logrotate_config(retention_period, self.charm.text_logs, compress)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 214, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-k8s-1: 01:43:09 ERROR juju.worker.uniter.operation hook "logging-relation-created" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...