[32mINFO    [0m pytest_operator.plugin:plugin.py:766 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_smoke:test_smoke.py:65 Deploying bundle
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm data-integrator from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-router-k8s from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-test-app from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm s3-integrator from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm self-signed-certificates from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm sysbench from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm grafana-agent-k8s from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-k8s from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application data-integrator with 1 unit using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-80
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-k8s with 1 unit using $addCharm-11
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-router-k8s-531
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-test-app using $addCharm-14
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/mysql-test-app-64
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application s3-integrator with 1 unit using $addCharm-17
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/s3-integrator-85
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application self-signed-certificates with 1 unit using $addCharm-20
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-214
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application sysbench with 1 unit using $addCharm-23
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/sysbench-123
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application grafana-agent-k8s with 1 unit using $addCharm-3
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-k8s-101
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-k8s with 3 units using $addCharm-6
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-k8s-208
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-data-integrator with 1 unit using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-80
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-12:backend-database
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> mysql-router-k8s:backend-database
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:certificates - $deploy-21:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:certificates - $deploy-21:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:s3-parameters - $deploy-18:s3-credentials
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:s3-parameters <-> s3-integrator:s3-credentials
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-1:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:database - $deploy-24:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:database <-> sysbench:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:grafana-dashboard - $deploy-4:grafana-dashboards-consumer
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:grafana-dashboard <-> grafana-agent-k8s:grafana-dashboards-consumer
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:metrics-endpoint - $deploy-4:metrics-endpoint
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:metrics-endpoint <-> grafana-agent-k8s:metrics-endpoint
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-7:logging - $deploy-4:logging-provider
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-k8s:logging <-> grafana-agent-k8s:logging-provider
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:database - $deploy-9:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:database <-> mysql-router-data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:grafana-dashboard - $deploy-4:grafana-dashboards-consumer
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:grafana-dashboard <-> grafana-agent-k8s:grafana-dashboards-consumer
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:metrics-endpoint - $deploy-4:metrics-endpoint
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:metrics-endpoint <-> grafana-agent-k8s:metrics-endpoint
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-12:logging - $deploy-4:logging-provider
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-k8s:logging <-> grafana-agent-k8s:logging-provider
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-9
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-12
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-15
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-18
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-1
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-21
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-24
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-4
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-7
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench
[32mINFO    [0m integration.test_smoke:test_smoke.py:45 Waiting for blocked: data-integrator, grafana-agent-k8s, mysql-router-data-integrator, s3-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:52 Waiting for waiting: mysql-router-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:70 Configuring s3-integrator credentials
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench, s3-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:45 Waiting for blocked: data-integrator, grafana-agent-k8s, mysql-router-data-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:52 Waiting for waiting: mysql-router-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:84 Configuring data-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench, s3-integrator, data-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:45 Waiting for blocked: grafana-agent-k8s, mysql-router-data-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:52 Waiting for waiting: mysql-router-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:93 Confirming data-integrator's database exists
[32mINFO    [0m integration.test_smoke:test_smoke.py:110 Configuring mysql-router-data-integrator
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench, s3-integrator, data-integrator, mysql-router-data-integrator, mysql-router-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:45 Waiting for blocked: grafana-agent-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:122 Confirming data-integrator's database exists
[32mINFO    [0m integration.test_smoke:test_smoke.py:128 Adding mysql-test-app unit
[33mWARNING [0m juju.application:application.py:150 adding units to a container-based model not supported, auto-switching to scale
[32mINFO    [0m integration.test_smoke:test_smoke.py:39 Waiting for active: mysql-k8s, self-signed-certificates, sysbench, s3-integrator, data-integrator, mysql-router-data-integrator, mysql-router-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:45 Waiting for blocked: grafana-agent-k8s
[32mINFO    [0m integration.test_smoke:test_smoke.py:52 Waiting for waiting: mysql-test-app
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.4    unsupported  01:32:09Z

App                           Version                  Status   Scale  Charm                     Channel      Rev  Address         Exposed  Message
data-integrator                                        active       1  data-integrator           latest/edge   80  10.152.183.115  no       
grafana-agent-k8s             0.40.4                   blocked      1  grafana-agent-k8s         latest/edge  101  10.152.183.211  no       Missing ['grafana-cloud-config']|['grafana-dashboards-provider'] for grafana-dashboards-consumer; ['grafana-cloud-con...
mysql-k8s                     8.0.37-0ubuntu0.22.04.3  waiting      3  mysql-k8s                 8.0/edge     208  10.152.183.253  no       installing agent
mysql-router-data-integrator                           waiting      1  data-integrator           latest/edge   80  10.152.183.106  no       installing agent
mysql-router-k8s              8.0.39-0ubuntu0.22.04.1  active       1  mysql-router-k8s          8.0/edge     531  10.152.183.171  no       
mysql-test-app                                         waiting    0/1  mysql-test-app            latest/edge   64  10.152.183.41   no       installing agent
s3-integrator                                          active       1  s3-integrator             latest/edge   85  10.152.183.173  no       
self-signed-certificates                               active       1  self-signed-certificates  latest/edge  214  10.152.183.204  no       
sysbench                                               active       1  sysbench                  latest/edge  123  10.152.183.220  no       

Unit                             Workload  Agent       Address      Ports  Message
data-integrator/0*               active    idle        10.1.146.8          
grafana-agent-k8s/0*             blocked   idle        10.1.146.18         Missing ['grafana-cloud-config']|['grafana-dashboards-provider'] for grafana-dashboards-consumer; ['grafana-cloud-con...
mysql-k8s/0*                     active    executing   10.1.146.19         Primary
mysql-k8s/1                      active    executing   10.1.146.20         
mysql-k8s/2                      active    idle        10.1.146.21         
mysql-router-data-integrator/0*  active    idle        10.1.146.13         
mysql-router-k8s/0*              active    executing   10.1.146.9          
mysql-test-app/0                 waiting   allocating  10.1.146.22         installing agent
s3-integrator/0*                 active    idle        10.1.146.10         
self-signed-certificates/0*      active    idle        10.1.146.11         
sysbench/0*                      active    idle        10.1.146.12         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-mysql-k8s-2: 01:27:27 ERROR unit.mysql-k8s/2.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:27:27 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:32 ERROR unit.mysql-k8s/0.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:27:32 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:27:34 ERROR unit.mysql-k8s/2.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:27:34 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:38 ERROR unit.mysql-k8s/0.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:27:39 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:27:45 ERROR unit.mysql-k8s/2.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:27:45 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:27:49 ERROR unit.mysql-k8s/0.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:27:50 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:27:58 ERROR unit.mysql-k8s/1.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:27:58 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:28:04 ERROR unit.mysql-k8s/1.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:28:05 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:28:05 ERROR unit.mysql-k8s/2.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:28:06 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:28:11 ERROR unit.mysql-k8s/0.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:28:11 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:28:16 ERROR unit.mysql-k8s/1.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:28:16 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:28:38 ERROR unit.mysql-k8s/1.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:28:38 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:28:45 ERROR unit.mysql-k8s/2.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:28:45 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:28:51 ERROR unit.mysql-k8s/0.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:28:51 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:29:20 ERROR unit.mysql-k8s/1.juju-log certificates:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 926, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 667, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1616, in cluster_metadata_exists
    output = self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:29:20 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...